### ISSUE TITLE
Wrong page number (NaN) in provider list UI

### ISSUE THREAD

**Issue by bingert** [FC4E-WP5/fc4eosc-PIDMR-ui#59]
<img width="372" alt="Screenshot 2024-08-19 at 12 26 48" src="https://github.com/user-attachments/assets/59d6bbae-f413-4da3-9b3b-4b30dba936b5">

**Comment by bingert** [comment]
I just realised that it only appears on the development URL

**Comment by themiszamani** [comment]
@bingert we fixed it could you please try again?
Best
Themis
